output_path = "/tmp/segment_backup/"
root_path = "/home/user" # Optional: Save segments relative to this path
post_script = "./example_config.sh"
log_file = "/tmp/segment_backup/segment_backup_%D.log"
compression_level = 6 # Tar/GZip compression level: 0 (No compression) - 9 (Most compression)
max_size_bytes = 2147483648 # Split files at this many bytes (2GB)

[segments]
documents = "/home/user/Documents"
nested_docs = "/home/user/Documents/SubFolder" # This should be excluded from Documents archive
pictures = "/home/user/Pictures"
